[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"

# Form processing
[[plugins]]
  package = "@netlify/plugin-forms"

# Redirect for thank you page
[[redirects]]
  from = "/contact"
  to = "/thank-you"
  status = 200
  conditions = {Method = ["POST"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache HTML pages
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"